//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAplicationMedioComunicacion.soapServicesMedioComunicacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="soapServicesMedioComunicacion.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert", ReplyAction="*")]
        webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertResponse insert(webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert", ReplyAction="*")]
        System.Threading.Tasks.Task<webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertResponse> insertAsync(webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert", Namespace="http://tempuri.org/", Order=0)]
        public webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequestBody Body;
        
        public insertRequest() {
        }
        
        public insertRequest(webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pais;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool estado;
        
        public insertRequestBody() {
        }
        
        public insertRequestBody(string nombre, string tipo, string pais, System.DateTime fecha, bool estado) {
            this.nombre = nombre;
            this.tipo = tipo;
            this.pais = pais;
            this.fecha = fecha;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertResponse", Namespace="http://tempuri.org/", Order=0)]
        public webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertResponseBody Body;
        
        public insertResponse() {
        }
        
        public insertResponse(webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insertResult;
        
        public insertResponseBody() {
        }
        
        public insertResponseBody(int insertResult) {
            this.insertResult = insertResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : webAplicationMedioComunicacion.soapServicesMedioComunicacion.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<webAplicationMedioComunicacion.soapServicesMedioComunicacion.WebService1Soap>, webAplicationMedioComunicacion.soapServicesMedioComunicacion.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertResponse webAplicationMedioComunicacion.soapServicesMedioComunicacion.WebService1Soap.insert(webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public int insert(string nombre, string tipo, string pais, System.DateTime fecha, bool estado) {
            webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequest inValue = new webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequest();
            inValue.Body = new webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.tipo = tipo;
            inValue.Body.pais = pais;
            inValue.Body.fecha = fecha;
            inValue.Body.estado = estado;
            webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertResponse retVal = ((webAplicationMedioComunicacion.soapServicesMedioComunicacion.WebService1Soap)(this)).insert(inValue);
            return retVal.Body.insertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertResponse> webAplicationMedioComunicacion.soapServicesMedioComunicacion.WebService1Soap.insertAsync(webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequest request) {
            return base.Channel.insertAsync(request);
        }
        
        public System.Threading.Tasks.Task<webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertResponse> insertAsync(string nombre, string tipo, string pais, System.DateTime fecha, bool estado) {
            webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequest inValue = new webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequest();
            inValue.Body = new webAplicationMedioComunicacion.soapServicesMedioComunicacion.insertRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.tipo = tipo;
            inValue.Body.pais = pais;
            inValue.Body.fecha = fecha;
            inValue.Body.estado = estado;
            return ((webAplicationMedioComunicacion.soapServicesMedioComunicacion.WebService1Soap)(this)).insertAsync(inValue);
        }
    }
}
